### ISSUE TITLE
rabbitmq: unable to open supervise/ok: file does not exist

### ISSUE THREAD

**Issue by priji** [hw-cookbooks/runit#155] opened 2015-09-25 18:36 UTC
Hi 

I get below error when i run the "sudo chef-server-ctl reconfigure" on ubuntu running on a docker container. Can you help on this 
[2015-09-25T18:30:50+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-09-25T18:30:50+00:00] ERROR: Exception handlers complete
Chef Client failed. 8 resources updated in 136.346012139 seconds
[2015-09-25T18:30:50+00:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2015-09-25T18:30:50+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[/opt/opscode/bin/private-chef-ctl start rabbitmq] (private-chef::rabbitmq line 85) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
STDOUT: warning: rabbitmq: unable to open supervise/ok: file does not exist
STDERR:
---- End output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
Ran /opt/opscode/bin/private-chef-ctl start rabbitmq returned 1

**Comment by cwjohnston** [comment] 2015-10-13 22:53
Closing as a duplicate of #142

**Closed by cwjohnston** 2015-10-13 22:53 UTC
