### ISSUE TITLE
RHEL 5 not supported

### ISSUE THREAD

**Issue by tas50** [hw-cookbooks/runit#179] opened 2016-02-16 22:04 UTC
It looks like a package is missing in the repo that's needed for RHEL 5

```
           * packagecloud_repo[imeyer/runit] action add
             * yum_package[pygpgme] action install
        * No candidate version available for pygpgme[2016-02-16T22:02:56+00:00] ERROR: yum_package[pygpgme] (/tmp/kitchen/cache/cookbooks/packagecloud/providers/repo.rb line 73) had an error: Chef::Exceptions::Package: No candidate version available for pygpgme; ignore_failure is set, continuing

        ================================================================================
        Error executing action `install` on resource 'yum_package[pygpgme]'
        ================================================================================

        Chef::Exceptions::Package
        -------------------------
        No candidate version available for pygpgme

        Cookbook Trace:
        ---------------
        /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'

        Resource Declaration:
        ---------------------
        # In /tmp/kitchen/cache/cookbooks/packagecloud/providers/repo.rb

         73:   package 'pygpgme' do
         74:     ignore_failure true
         75:   end
         76:

        Compiled Resource:
        ------------------
        # Declared in /tmp/kitchen/cache/cookbooks/packagecloud/providers/repo.rb:73:in `install_rpm'

        yum_package("pygpgme") do
          package_name "pygpgme"
          action [:install]
          ignore_failure true
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          declared_type :package
          cookbook_name "runit"
          flush_cache {:before=>false, :after=>false}
        end
```

**Comment by cwjohnston** [comment] 2016-04-27 20:30
This issue appears to be a duplicate of #86

**Comment by cwjohnston** [comment] 2016-04-27 20:32
Ok, not necessarily a dupe but somewhat related.

**Closed** 2016-06-02 19:14 UTC
Labels: in progress
